services:
  db:
    image: postgres:16-alpine
    container_name: ms-simulation-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ms-simulation-db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


#  rabbitmq:
 #   image: rabbitmq:3-management
  #  container_name: ms-simulation-rabbitmq
   # restart: always
  #  ports:
   #   - "5672:5672"
    #  - "15672:15672"

volumes:
  postgres_data:
