spring:
  application:
    name: MS-SIMULATION
  liquibase:
    enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5433/ms-simulation-db
    username: admin
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        auto-startup: false
